
from .env_maker2 import Toyenv
sc2_map_list = ['3m',
            '8m',
            '25m',
            '5m_vs_6m',
            '8m_vs_9m',
            '10m_vs_11m',
            '27m_vs_30m',
            'MMM',
            'MMM2',
            '2s3z',
            '3s5z',
            '3s5z_vs_3s6z',
            '3s_vs_3z',
            '3s_vs_4z',
            '3s_vs_5z',
            '1c3s5z',
            '2m_vs_1z',
            'corridor',
            '6h_vs_8z',
            '2s_vs_1sc',
            'so_many_baneling',
            'bane_vs_bane',
            '2c_vs_64zg']
